### ISSUE TITLE
Activity Diagram

### ISSUE THREAD

**Issue by MrMoon** [MrMoon/Vision#36]
Use the Activity Diagrams to illustrate the flow of control in a system and refer to the steps involved in the execution of a use case.
- Use cases include (these are in order of importance, i.e: the first use case is the most important should be worked on first):
     - [x] Video and Image Enhancer
     - [x] Video and Image Denoising
     - [x] Image to Data

**Comment by MohaDarkness** [comment]
You sure about the order of importance? @MrMoon

**Comment by MrMoon** [comment]
> You sure about the order of importance? @MrMoon 

Positive. Our core depends on video and image enhancement. Denoising and other features can be done later.

If you are talking about how denoising is a pre-processor for enhancement, yeah you are right but you can just reference the functions without showing what it do (abstraction), like a normal function call.

**Comment by MohaDarkness** [comment]
If I'm getting you right, then this is how the activities should be ordered
in the activity diagram.
Please confirm it if it's correct (or making sense at least :P) and feel
free to tell if it needs any improvements. (all the ways I need to change
some shapes before we submit it).

[image: Vision.jpg]

**Comment by MrMoon** [comment]
> If I'm getting you right, then this is how the activities should be ordered in the activity diagram. Please confirm it if it's correct (or making sense at least :P) and feel free to tell if it needs any improvements. (all the ways I need to change some shapes before we submit it). [image: Vision.jpg]
> […](#)

The picture is not attached, 
open a new branch, and use [draw.io](draw.io) to make the diagram, make sure to save the file in Drawing under the Model directory in the repo, 
and open a pull request from the new branch
